stages:
  load_data:
    cmd: python src/load_and_save.py --config=params.yaml
    deps:
      - src/load_and_save.py
    params:
      - data_source.s3_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - artifacts/raw_local_data_dir/data.csv
    params:
      - artifacts.raw_local_data
      - artifacts.split_data.processed_data_dir
      - artifacts.split_data.train_path
      - artifacts.split_data.test_path
      - base.random_state
      - base.test_size
    outs:
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv