stages:
  load_data:
    cmd: python src/load_and_save.py --config=params.yaml
    deps:
      - src/load_and_save.py
      - src/utils/common_utils.py
    params:
      - data_source.s3_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - artifacts/raw_local_data_dir/data.csv
      - src/utils/common_utils.py
    params:
      - artifacts.raw_local_data
      - artifacts.split_data.processed_data_dir
      - artifacts.split_data.train_path
      - artifacts.split_data.test_path
      - base.random_state
      - base.test_size
    outs:
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv
  

  train:
    cmd: python src/train.py --config=params.yaml
    deps:
      - src/train.py
      - artifacts/processed_data/train.csv
      - src/utils/common_utils.py
    params:
      - artifacts.split_data.train_path
      - base.random_state
      - base.target_col
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - artifacts/report/params.json:
          cache: false
    outs:
      - artifacts/saved_models/model.joblib

  evaluate:
    cmd: python src/evaluate.py --config=params.yaml
    deps:
      - src/evaluate.py
      - artifacts/processed_data/test.csv
      - artifacts/saved_models/model.joblib
      - src/utils/common_utils.py
    params:
      - artifacts.split_data.test_path
      - base.target_col

    metrics:
      - artifacts/report/scores.json:
          cache: false
     